-- MySQL Script generated by MySQL Workbench
-- Tue Oct 22 19:47:31 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema actividad1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema actividad1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `actividad1` DEFAULT CHARACTER SET utf8 ;
USE `actividad1` ;

-- -----------------------------------------------------
-- Table `actividad1`.`Departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `actividad1`.`Departamentos` (
  `cod_departamento` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(50) NULL,
  `ubicacion` VARCHAR(100) NULL,
  PRIMARY KEY (`cod_departamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `actividad1`.`Empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `actividad1`.`Empleados` (
  `dni` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(50) NULL,
  `sueldo` INT NULL,
  `cod_departamento` VARCHAR(10) NULL,
  `Departamentos_cod_departamento` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`dni`),
  INDEX `fk_Empleados_Departamentos_idx` (`Departamentos_cod_departamento` ASC) VISIBLE,
  CONSTRAINT `fk_Empleados_Departamentos`
    FOREIGN KEY (`Departamentos_cod_departamento`)
    REFERENCES `actividad1`.`Departamentos` (`cod_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;